name: EpicRPGGornik
version: 2.0.1
main: me.Vark123.EpicRPGGornik.Main
author: Vark123
depend: [NBTAPI,MythicMobs,MultiWorld,KeepChunks,CalendarEvents,EpicRPG]
api-version: 1.18

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5

commands:
  oremerchant:
    aliases: [omerchant,omerch,okupiec]
  tanalorrrepair:
  pickaxeupgrade: